-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- DONORS TABLE
create table donors (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  phone_number text not null unique,
  blood_group text not null,
  city text not null,
  is_active boolean default true,
  created_at timestamp with time zone default now()
);

-- REQUESTS TABLE
create table requests (
  id uuid primary key default uuid_generate_v4(),
  receiver_name text not null,
  receiver_phone text not null,
  blood_group_required text not null,
  location text not null,
  status text not null default 'open' check (status in ('open', 'closed')),
  created_at timestamp with time zone default now(),
  closed_at timestamp with time zone
);

-- NOTIFICATIONS TABLE
create table notifications (
  id bigint generated by default as identity primary key,
  request_id uuid references requests(id) not null,
  donor_id uuid references donors(id) not null,
  sent_at timestamp with time zone default now(),
  delivery_status text default 'sent'
);

-- ROW LEVEL SECURITY (RLS)
-- Enable RLS on all tables
alter table donors enable row level security;
alter table requests enable row level security;
alter table notifications enable row level security;

-- Policies for Donors
-- Allow public insert (registration)
create policy "Allow public insert for donors"
  on donors for insert
  with check (true);

-- Allow public read (for matching logic - in a real app this might be restricted, 
-- but for this MVP we need edge functions/anon to read it or use service role)
-- For privacy, purely public read is dangerous. 
-- However, the requirement implies we need to query it.
-- We will allow service_role key (Edge Functions) to bypass RLS.
-- For the frontend, no direct read access to full donor list is laid out in requirements.
-- We'll add a policy that allows reading only if you are the owner (not applicable without auth)
-- OR effectively, we might not need public read for donors if only edge functions access it.
-- But wait, "Receiver Form" -> "Query donors" -> "Trigger backend logic".
-- If the matching logic is in an Edge Function, it receives the request and does the querying.
-- The Edge Function runs with service_role usually, so it bypasses RLS.
-- So we can keep Donors private from public SELECT.

-- Policies for Requests
-- Allow public insert (submitting a request)
create policy "Allow public insert for requests"
  on requests for insert
  with check (true);

-- Allow public read for request pages (anyone with link can view)
create policy "Allow public read for requests"
  on requests for select
  using (true);
  
-- Allow public update (Closing the request)
-- In a real app we'd need auth or a signed token. 
-- For this MVP, we'll allow update if they have the ID (which is the public link essentially).
create policy "Allow public update for requests"
  on requests for update
  using (true);

-- Policies for Notifications
-- Mostly for backend use, but maybe useful for debugging.
-- We'll leave it restricted to service_role mostly.
